#!/bin/sh
 sudo apt update -y
 sudo apt install ansible -y
 sudo touch hosts
 sudo touch playbook
 sudo echo  "[servers]
  ansible_cl1 ansible_host=192.168.0.114
  ansible_cl2 ansible_host=192.168.0.115
  ansible_cl3 ansible_host=192.168.0.0

[all:vars]
  ansible_python_interpreter=/usr/bin/python3" > hosts
 ansible all -m ping -u root
# sudo mkdir /etc/ansible/
# sudo cp hosts /etc/ansible/
 cd
 #ssh-keygen
 ssh-keygen -q -f /home/zkaster/.ssh/id_rsa -N "" 
 #ssh-copy-id 
